[package]
name = "stellatune-asio-proto"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
serde.workspace = true
postcard = { workspace = true, features = ["use-std"] }
thiserror.workspace = true

[lints]
workspace = true

