[package]
name = "stellatune-runtime"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
async-trait.workspace = true
crossbeam-channel.workspace = true
futures-util.workspace = true
tokio.workspace = true

[lints]
workspace = true
