[package]
name = "stellatune-plugin-sdk"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
stellatune-plugin-api.workspace = true
stellatune-plugin-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait = "0.1"


[lints]
workspace = true


