[package]
name = "stellatune-plugins"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow.workspace = true
libloading.workspace = true
serde.workspace = true
toml.workspace = true
walkdir.workspace = true
tracing.workspace = true

stellatune-plugin-api.workspace = true

[dev-dependencies]
tempfile = "3.20.0"
stellatune-decode.workspace = true
