[package]
name = "stellatune-ffi"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
name = "stellatune_ffi"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
anyhow = "1"
flutter_rust_bridge = "=2.11.1"

stellatune-audio = { path = "../stellatune-audio" }
stellatune-core = { path = "../stellatune-core" }
