[package]
name = "stellatune-ffi"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
name = "stellatune_ffi"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
anyhow.workspace = true
flutter_rust_bridge.workspace = true

stellatune-audio.workspace = true
stellatune-core.workspace = true
