[package]
name = "stellatune-plugin-netease-decoder"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
stellatune-plugin-sdk.workspace = true
symphonia.workspace = true

[lints]
workspace = true
