[package]
name = "stellatune-core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = []
frb = []

[dependencies]
flutter_rust_bridge.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true

