[package]
name = "stellatune-plugin-ncm-wasm-decoder"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
stellatune-wasm-plugin-sdk.workspace = true
symphonia.workspace = true
ncmdump = "0.8.0"

[lints]
workspace = true
